name: ci
on:
  push:
    branches:
      - main
      - 'FEATURE-*' 
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install poetry
        run: pipx install poetry
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: install deps
        run: |
          poetry env use "3.11"
          poetry install --no-interaction
      - name: lint and format
        run: |
          poetry run isort . --check-only
          poetry run black --check .
          poetry run flake8 .
          poetry run pylint $(find ./dlpr_code -name "*.py" | xargs)
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install poetry
        run: pipx install poetry
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: install deps
        run: |
          poetry env use "3.11"
          poetry install --no-interaction
      - name: test 
        run: poetry run pytest 